version: '3'

services:
  certbot:
    image: certbot/dns-google:latest
    container_name: certbot
    restart: always
    command: ""
    entrypoint: sh -c "trap exit TERM; while :; do /certbot; sleep 24h & wait $${!}; done;"
    volumes:
      - "letsencrypt:/etc/letsencrypt"
      - "./certbot.py:/certbot:ro"
    environment:
      - TERM="xterm"
      - EMAIL=${EMAIL}
      - WEB_DOMAINS=${WEB_DOMAINS}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
    networks:
      - backend

volumes:
  letsencrypt:

networks:
  frontend:
  backend:

x-disabled:
  mc-router:
    image: itzg/mc-router:latest
    container_name: mc-router
    restart: always
    ports:
      - 25565:25565
    command: --mapping=${MC_EXTERNAL_DOMAIN}=tusbv13alpha:25565

  tusbv13alpha:
    image: itzg/minecraft-server:latest
    container_name: tusb
    restart: always
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.17.1"
      MEMORY: "6G"
      MOTD: "TheUnusualSkyBlock v13.1.1 alpha"
      OVERRIDE_SERVER_PROPERTIES: true
      RESOURCE_PACK: "https://www.dropbox.com/s/9ombtpecc6kxgqj/TheUnusualResourcePack_13.1.1-alpha.zip?dl=1"
      RESOURCE_PACK_SHA1: "a32d0d073781a7da6f32a3f12df015d14cd925d6"
      RESOURCE_PACK_ENFORCE: true
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      ENABLE_COMMAND_BLOCK: true
      ALLOW_FLIGHT: true
      SPAWN_PROTECTION: 0
    volumes:
      - ./minecraft:/data
    tty: true
    stdin_open: true

  ark:
    image: turzam/ark:latest
    container_name: ark
    restart: always
    ports:
      - 7777:7777
      - 7777:7777/udp
      - 7778:7778
      - 7778:7778/udp
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - "./ark:/ark"
    environment:
      - SESSIONNAME=${SESSIONNAME}
      - SERVERMAP=${SERVERMAP}
      - SERVERPASSWORD=${SERVERPASSWORD}
      - ADMINPASSWORD=${ADMINPASSWORD}
      - GIT_TAG=${GIT_TAG}
      - NBPLAYERS=64
      - SERVERPORT=27015
      - STEAMPORT=7778
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - BACKUPONSTOP=1
      - WARNONSTOP=0
      - TZ=Asia/Tokyo
      - UID=1000
      - GID=1000

  7dtd:
    image: vinanrra/7dtd-server
    container_name: 7dtd
    restart: always
    ports:
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp
    environment:
      - START_MODE=1
      - VERSION=stable
      - PUID=1000
      - PGID=1000
      - TimeZone=Asia/Tokyo
    volumes:
      - ./7dtd/7DaysToDie:/home/sdtdserver/.local/share/7DaysToDie/
      - ./7dtd/LGSM-Config:/home/sdtdserver/lgsm/config-lgsm/sdtdserver
      - ./7dtd/ServerFiles:/home/sdtdserver/serverfiles/
      - ./7dtd/log:/home/sdtdserver/log/
      - ./7dtd/backups:/home/sdtdserver/lgsm/backup/
